/**
 * 한의사AI 샘플 데이터 생성 스크립트
 *
 * MVP용: 실제 크롤링 대신 한의학 지식 기반 고품질 샘플 데이터를 JSON으로 생성
 *
 * 실행: npx tsx scripts/collect/generate-samples.ts
 * 결과: data/raw/ 하위에 JSON 파일 생성
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type {
  DongeuibogamCollection,
  DongeuibogamEntry,
  HerbCollection,
  HerbEntry,
  PrescriptionCollection,
  PrescriptionEntry,
  SourceMeta,
} from './types';

// ─── 경로 설정 ───

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '..', '..');
const DATA_DIR = join(PROJECT_ROOT, 'data', 'raw');
const DONGEUIBOGAM_DIR = join(DATA_DIR, 'dongeuibogam');
const HERBS_DIR = join(DATA_DIR, 'herbs');
const PRESCRIPTIONS_DIR = join(DATA_DIR, 'prescriptions');

const NOW = new Date().toISOString();

function makeSource(origin: string, note?: string): SourceMeta {
  return {
    origin,
    method: 'sample-generation',
    collectedAt: NOW,
    note: note ?? 'MVP 샘플 데이터 — 한의학 문헌 기반 수작업 정리',
  };
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 1. 동의보감 경전 텍스트 (내경편 핵심 장절 15개)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function generateDongeuibogam(): DongeuibogamCollection {
  const entries: DongeuibogamEntry[] = [
    {
      id: 'DEB-NE-001',
      section: '내경편',
      volume: 1,
      chapter: '身形',
      subchapter: '身形臟腑圖',
      originalText: '天地之間 萬物之中 惟人最貴 人之所貴 莫貴於生',
      translatedText: '천지 사이 만물 가운데 오직 사람이 가장 귀하고, 사람에게 귀한 것 중에 생명보다 귀한 것은 없다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-002',
      section: '내경편',
      volume: 1,
      chapter: '精',
      subchapter: '精爲一身之主',
      originalText: '精者 身之本也 男子二八而精通 女子二七而天癸至',
      translatedText: '정(精)은 몸의 근본이다. 남자는 이팔(16세)에 정이 통하고, 여자는 이칠(14세)에 천계(天癸)가 이른다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-003',
      section: '내경편',
      volume: 1,
      chapter: '氣',
      subchapter: '氣爲保生之主',
      originalText: '人之有生 全賴此氣 氣聚則生 氣散則死',
      translatedText: '사람이 살아 있는 것은 전적으로 이 기(氣)에 달려 있다. 기가 모이면 살고 기가 흩어지면 죽는다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-004',
      section: '내경편',
      volume: 1,
      chapter: '神',
      subchapter: '神爲一身之主宰',
      originalText: '神者 心之主也 心者 神之舍也 心安則神安 心不安則神不安',
      translatedText: '신(神)은 심(心)의 주인이고, 심은 신이 머무는 곳이다. 마음이 편안하면 신이 편안하고, 마음이 편안하지 않으면 신이 편안하지 않다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-005',
      section: '내경편',
      volume: 1,
      chapter: '血',
      subchapter: '血爲百體之榮養',
      originalText: '血者 水穀之精氣也 生化於脾 總統於心 藏受於肝 宣布於肺 施泄於腎',
      translatedText: '혈(血)은 수곡(음식)의 정기이다. 비장에서 생성되고, 심장에서 총괄하며, 간에서 저장하고, 폐에서 펼쳐 보내며, 신장에서 배설한다.',
      category: '진단',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-006',
      section: '내경편',
      volume: 2,
      chapter: '夢',
      subchapter: '夢之所因',
      originalText: '肝氣盛則夢怒 肺氣盛則夢恐懼哭泣 心氣盛則夢喜笑',
      translatedText: '간기(肝氣)가 성하면 꿈에서 노하고, 폐기(肺氣)가 성하면 꿈에서 두려워하며 울고, 심기(心氣)가 성하면 꿈에서 기뻐하며 웃는다.',
      category: '진단',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-007',
      section: '내경편',
      volume: 2,
      chapter: '聲音',
      subchapter: '五聲',
      originalText: '肝在聲爲呼 心在聲爲笑 脾在聲爲歌 肺在聲爲哭 腎在聲爲呻',
      translatedText: '간은 소리로는 부르짖음이고, 심은 웃음이며, 비는 노래이고, 폐는 울음이며, 신은 신음이다.',
      category: '진단',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-008',
      section: '내경편',
      volume: 1,
      chapter: '五臟六腑',
      subchapter: '肝臟',
      originalText: '肝者 將軍之官 謀慮出焉 肝藏血 血舍魂',
      translatedText: '간은 장군의 관직이니 꾀와 생각이 여기에서 나온다. 간은 혈을 저장하고 혈은 혼(魂)이 깃드는 곳이다.',
      category: '장부',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-009',
      section: '내경편',
      volume: 1,
      chapter: '五臟六腑',
      subchapter: '心臟',
      originalText: '心者 君主之官也 神明出焉 心藏脈 脈舍神',
      translatedText: '심은 군주의 관직이니 신명(神明)이 여기에서 나온다. 심은 맥을 저장하고 맥은 신(神)이 깃드는 곳이다.',
      category: '장부',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-010',
      section: '내경편',
      volume: 1,
      chapter: '五臟六腑',
      subchapter: '脾臟',
      originalText: '脾者 倉廩之官 五味出焉 脾藏營 營舍意',
      translatedText: '비(脾)는 창름의 관직이니 오미(五味)가 여기에서 나온다. 비는 영(營)을 저장하고, 영은 의(意)가 깃드는 곳이다.',
      category: '장부',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-011',
      section: '내경편',
      volume: 1,
      chapter: '五臟六腑',
      subchapter: '肺臟',
      originalText: '肺者 相傅之官 治節出焉 肺藏氣 氣舍魄',
      translatedText: '폐는 상부(재상)의 관직이니 치절(治節, 다스림)이 여기에서 나온다. 폐는 기(氣)를 저장하고, 기는 백(魄)이 깃드는 곳이다.',
      category: '장부',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-012',
      section: '내경편',
      volume: 1,
      chapter: '五臟六腑',
      subchapter: '腎臟',
      originalText: '腎者 作强之官 伎巧出焉 腎藏精 精舍志',
      translatedText: '신(腎)은 작강의 관직이니 재주와 솜씨가 여기에서 나온다. 신은 정(精)을 저장하고, 정은 지(志)가 깃드는 곳이다.',
      category: '장부',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-013',
      section: '내경편',
      volume: 2,
      chapter: '津液',
      subchapter: '津液之生',
      originalText: '水穀入於口 其味有五 各注其海 津液各走其道',
      translatedText: '수곡(음식)이 입으로 들어가면 그 맛이 다섯 가지이고, 각각 자기의 바다(海)에 모이며, 진액은 각기 자기의 길을 따라간다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-014',
      section: '내경편',
      volume: 3,
      chapter: '大便',
      subchapter: '大便秘結',
      originalText: '大便秘結者 由五臟不調 陰陽偏勝 或熱盛傷津 或氣虛不運',
      translatedText: '대변이 막히는 것은 오장이 고르지 못하고, 음양이 한쪽으로 치우쳐 이기거나, 열이 성하여 진액이 상하거나, 기가 허하여 운행하지 못하기 때문이다.',
      category: '치료',
      source: makeSource('동의보감 내경편'),
    },
    {
      id: 'DEB-NE-015',
      section: '내경편',
      volume: 1,
      chapter: '養性',
      subchapter: '養性總論',
      originalText: '善養生者 養內 不善養生者 養外 養內者以恬臟腑 調順血脈',
      translatedText: '양생을 잘하는 사람은 안(內)을 기르고, 양생을 잘 못하는 사람은 밖(外)을 기른다. 안을 기르는 것은 장부를 편안히 하고, 혈맥을 조순(調順)하는 것이다.',
      category: '양생',
      source: makeSource('동의보감 내경편'),
    },
  ];

  return {
    dataType: 'dongeuibogam',
    version: '1.0.0-sample',
    generatedAt: NOW,
    totalCount: entries.length,
    entries,
  };
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 2. 약재 데이터 (대표 약재 50건)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function generateHerbs(): HerbCollection {
  const entries: HerbEntry[] = [
    // ── 補氣藥 ──
    {
      id: 'HERB-001',
      nameKo: '인삼',
      nameHanja: '人蔘',
      nameLatin: 'Panax ginseng C.A.Mey.',
      properties: { nature: '微溫', taste: ['甘', '微苦'] },
      meridians: ['脾', '肺', '心'],
      effects: ['大補元氣', '復脈固脫', '補脾益肺', '生津養血', '安神益智'],
      indications: ['기허핍력(氣虛乏力)', '식소변당(食少便溏)', '심계실면(心悸失眠)', '건망(健忘)', '구탈(口渴)'],
      cautions: ['실열증(實熱證) 금기', '여로(藜蘆)와 배오(配伍) 금기'],
      category: '補氣藥',
      dosage: '3~9g',
      source: makeSource('OASIS 한약재 DB', '국가한의약지식정보포털 기반'),
    },
    {
      id: 'HERB-002',
      nameKo: '황기',
      nameHanja: '黃芪',
      nameLatin: 'Astragalus membranaceus (Fisch.) Bge.',
      properties: { nature: '微溫', taste: ['甘'] },
      meridians: ['脾', '肺'],
      effects: ['補氣升陽', '固表止汗', '利水消腫', '生津養血', '托毒排膿'],
      indications: ['기허핍력', '식소변당', '중기하함(中氣下陷)', '자한(自汗)', '수종(水腫)'],
      cautions: ['표실사성(表實邪盛) 금기', '음허양항(陰虛陽亢) 주의'],
      category: '補氣藥',
      dosage: '9~30g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-003',
      nameKo: '감초',
      nameHanja: '甘草',
      nameLatin: 'Glycyrrhiza uralensis Fisch.',
      properties: { nature: '平', taste: ['甘'] },
      meridians: ['心', '肺', '脾', '胃'],
      effects: ['補脾益氣', '淸熱解毒', '祛痰止咳', '緩急止痛', '調和諸藥'],
      indications: ['비위허약(脾胃虛弱)', '인후종통(咽喉腫痛)', '해수(咳嗽)', '완복동통(脘腹疼痛)'],
      cautions: ['감수(甘遂), 대극(大戟), 원화(芫花), 해조(海藻)와 배오 금기', '장기 대량 복용 시 부종 주의'],
      category: '補氣藥',
      dosage: '2~10g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-004',
      nameKo: '백출',
      nameHanja: '白朮',
      nameLatin: 'Atractylodes macrocephala Koidz.',
      properties: { nature: '溫', taste: ['甘', '苦'] },
      meridians: ['脾', '胃'],
      effects: ['補氣健脾', '燥濕利水', '止汗', '安胎'],
      indications: ['비기허약(脾氣虛弱)', '식소창만(食少脹滿)', '수종(水腫)', '자한(自汗)'],
      cautions: ['음허조갈(陰虛燥渴) 주의'],
      category: '補氣藥',
      dosage: '6~12g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-005',
      nameKo: '산약',
      nameHanja: '山藥',
      nameLatin: 'Dioscorea opposita Thunb.',
      properties: { nature: '平', taste: ['甘'] },
      meridians: ['脾', '肺', '腎'],
      effects: ['補脾養胃', '生津益肺', '補腎澁精'],
      indications: ['비허설사(脾虛泄瀉)', '폐허해수(肺虛咳嗽)', '신허유정(腎虛遺精)', '소갈(消渴)'],
      cautions: ['습성 체질에 과량 주의'],
      category: '補氣藥',
      dosage: '15~30g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 補血藥 ──
    {
      id: 'HERB-006',
      nameKo: '당귀',
      nameHanja: '當歸',
      nameLatin: 'Angelica sinensis (Oliv.) Diels',
      properties: { nature: '溫', taste: ['甘', '辛'] },
      meridians: ['肝', '心', '脾'],
      effects: ['補血活血', '調經止痛', '潤腸通便'],
      indications: ['혈허위황(血虛萎黃)', '월경부조(月經不調)', '경폐통경(經閉痛經)', '허한복통(虛寒腹痛)', '장조변비(腸燥便秘)'],
      cautions: ['습성설사(濕盛泄瀉) 금기'],
      category: '補血藥',
      dosage: '6~12g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-007',
      nameKo: '숙지황',
      nameHanja: '熟地黃',
      nameLatin: 'Rehmannia glutinosa (Gaertn.) Libosch.',
      properties: { nature: '微溫', taste: ['甘'] },
      meridians: ['肝', '腎'],
      effects: ['補血滋陰', '益精塡髓'],
      indications: ['혈허위황', '심계정충(心悸怔忡)', '월경부조', '간신음허(肝腎陰虛)', '요슬산연(腰膝痠軟)'],
      cautions: ['비위허약으로 식소복만(食少腹滿) 시 주의', '성질이 끈적하여 소화 장애 유발 가능'],
      category: '補血藥',
      dosage: '9~15g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-008',
      nameKo: '백작약',
      nameHanja: '白芍藥',
      nameLatin: 'Paeonia lactiflora Pall.',
      properties: { nature: '微寒', taste: ['苦', '酸'] },
      meridians: ['肝', '脾'],
      effects: ['養血斂陰', '柔肝止痛', '平抑肝陽'],
      indications: ['혈허위황', '월경부조', '자한도한(自汗盜汗)', '협늑동통(脇肋疼痛)', '사지경련(四肢痙攣)'],
      cautions: ['여로(藜蘆)와 배오 금기'],
      category: '補血藥',
      dosage: '6~15g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-009',
      nameKo: '하수오',
      nameHanja: '何首烏',
      nameLatin: 'Polygonum multiflorum Thunb.',
      properties: { nature: '微溫', taste: ['苦', '甘', '澁'] },
      meridians: ['肝', '心', '腎'],
      effects: ['補肝腎', '益精血', '烏鬚髮', '解毒'],
      indications: ['간신부족(肝腎不足)', '수발조백(鬚髮早白)', '요슬산연', '유정(遺精)'],
      cautions: ['대황하지(大便溏泄) 금기', '간독성 보고 있어 장기 복용 주의'],
      category: '補血藥',
      dosage: '6~12g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-010',
      nameKo: '아교',
      nameHanja: '阿膠',
      nameLatin: 'Colla Corii Asini',
      properties: { nature: '平', taste: ['甘'] },
      meridians: ['肺', '肝', '腎'],
      effects: ['補血滋陰', '潤燥止血'],
      indications: ['혈허위황', '현훈심계(眩暈心悸)', '폐조해수(肺燥咳嗽)', '토혈(吐血)', '붕루(崩漏)'],
      cautions: ['비위허약 시 소화 장애 주의', '습탁내성(濕濁內盛) 금기'],
      category: '補血藥',
      dosage: '3~9g (烊化)',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 解表藥 ──
    {
      id: 'HERB-011',
      nameKo: '마황',
      nameHanja: '麻黃',
      nameLatin: 'Ephedra sinica Stapf',
      properties: { nature: '溫', taste: ['辛', '微苦'] },
      meridians: ['肺', '膀胱'],
      effects: ['發汗散寒', '宣肺平喘', '利水消腫'],
      indications: ['풍한감모(風寒感冒)', '해수천식(咳嗽喘息)', '풍수부종(風水浮腫)'],
      cautions: ['체허자한(體虛自汗) 금기', '고혈압, 실면(失眠) 환자 주의'],
      category: '解表藥',
      dosage: '2~9g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-012',
      nameKo: '계지',
      nameHanja: '桂枝',
      nameLatin: 'Cinnamomum cassia (L.) J.Presl',
      properties: { nature: '溫', taste: ['辛', '甘'] },
      meridians: ['心', '肺', '膀胱'],
      effects: ['發汗解肌', '溫通經脈', '助陽化氣', '平衝降逆'],
      indications: ['풍한감모', '한응혈체(寒凝血滯)', '관절비통(關節痹痛)', '담음(痰飲)', '수종'],
      cautions: ['온열병(溫熱病) 금기', '음허화왕(陰虛火旺) 금기', '임산부 주의'],
      category: '解表藥',
      dosage: '3~9g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-013',
      nameKo: '갈근',
      nameHanja: '葛根',
      nameLatin: 'Pueraria lobata (Willd.) Ohwi',
      properties: { nature: '涼', taste: ['甘', '辛'] },
      meridians: ['脾', '胃'],
      effects: ['解肌退熱', '透疹', '生津止渴', '升陽止瀉'],
      indications: ['외감발열(外感發熱)', '항강(項强)', '마진부투(麻疹不透)', '열병구갈(熱病口渴)', '설사(泄瀉)'],
      cautions: ['위한구토(胃寒嘔吐) 주의'],
      category: '解表藥',
      dosage: '9~15g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-014',
      nameKo: '방풍',
      nameHanja: '防風',
      nameLatin: 'Saposhnikovia divaricata (Turcz.) Schischk.',
      properties: { nature: '微溫', taste: ['辛', '甘'] },
      meridians: ['膀胱', '肝', '脾'],
      effects: ['祛風解表', '勝濕止痛', '止痙'],
      indications: ['감모두통(感冒頭痛)', '풍습비통(風濕痹痛)', '풍진소양(風疹瘙癢)', '파상풍(破傷風)'],
      cautions: ['혈허발경(血虛發痙) 금기', '음허화왕 금기'],
      category: '解表藥',
      dosage: '5~10g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-015',
      nameKo: '형개',
      nameHanja: '荊芥',
      nameLatin: 'Schizonepeta tenuifolia (Benth.) Briq.',
      properties: { nature: '微溫', taste: ['辛'] },
      meridians: ['肺', '肝'],
      effects: ['祛風解表', '透疹消瘡', '止血'],
      indications: ['감모두통', '마진부투', '풍진소양', '창양초기(瘡瘍初起)', '토혈(吐血)'],
      cautions: ['표허자한(表虛自汗) 금기', '음허두통(陰虛頭痛) 금기'],
      category: '解表藥',
      dosage: '5~10g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-016',
      nameKo: '세신',
      nameHanja: '細辛',
      nameLatin: 'Asarum sieboldii Miq.',
      properties: { nature: '溫', taste: ['辛'] },
      meridians: ['心', '肺', '腎'],
      effects: ['祛風散寒', '通竅', '止痛', '溫肺化飮'],
      indications: ['풍한두통(風寒頭痛)', '비색(鼻塞)', '치통(齒痛)', '풍한해수(風寒咳嗽)', '담음(痰飮)'],
      cautions: ['용량 과다 금기 (독성)', '반하(半夏), 여로(藜蘆)와 함께 주의', '기허다한(氣虛多汗) 금기'],
      category: '解表藥',
      dosage: '1~3g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 清熱藥 ──
    {
      id: 'HERB-017',
      nameKo: '황금',
      nameHanja: '黃芩',
      nameLatin: 'Scutellaria baicalensis Georgi',
      properties: { nature: '寒', taste: ['苦'] },
      meridians: ['肺', '膽', '脾', '大腸', '小腸'],
      effects: ['淸熱燥濕', '瀉火解毒', '止血', '安胎'],
      indications: ['습온(濕溫)', '서습흉민(暑濕胸悶)', '황달(黃疸)', '폐열해수(肺熱咳嗽)', '태동불안(胎動不安)'],
      cautions: ['비위허한(脾胃虛寒) 금기'],
      category: '清熱藥',
      dosage: '3~10g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-018',
      nameKo: '황련',
      nameHanja: '黃連',
      nameLatin: 'Coptis chinensis Franch.',
      properties: { nature: '寒', taste: ['苦'] },
      meridians: ['心', '脾', '胃', '肝', '膽', '大腸'],
      effects: ['淸熱燥濕', '瀉火解毒'],
      indications: ['습열사리(濕熱痢疾)', '구토탄산(嘔吐呑酸)', '심화항성(心火亢盛)', '목적(目赤)', '구창(口瘡)'],
      cautions: ['비위허한 금기', '음허번열(陰虛煩熱) 주의'],
      category: '清熱藥',
      dosage: '2~5g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-019',
      nameKo: '황백',
      nameHanja: '黃柏',
      nameLatin: 'Phellodendron amurense Rupr.',
      properties: { nature: '寒', taste: ['苦'] },
      meridians: ['腎', '膀胱'],
      effects: ['淸熱燥濕', '瀉火除蒸', '解毒療瘡'],
      indications: ['습열대하(濕熱帶下)', '열림(熱淋)', '골증조열(骨蒸潮熱)', '도한(盜汗)', '유정(遺精)'],
      cautions: ['비위허한 금기'],
      category: '清熱藥',
      dosage: '3~12g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-020',
      nameKo: '치자',
      nameHanja: '梔子',
      nameLatin: 'Gardenia jasminoides J.Ellis',
      properties: { nature: '寒', taste: ['苦'] },
      meridians: ['心', '肺', '三焦'],
      effects: ['瀉火除煩', '淸熱利濕', '涼血解毒'],
      indications: ['열병심번(熱病心煩)', '황달(黃疸)', '혈림삽통(血淋澁痛)', '목적종통(目赤腫痛)', '화독창양(火毒瘡瘍)'],
      cautions: ['비허변당(脾虛便溏) 금기'],
      category: '清熱藥',
      dosage: '6~10g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-021',
      nameKo: '석고',
      nameHanja: '石膏',
      nameLatin: 'Gypsum Fibrosum',
      properties: { nature: '大寒', taste: ['甘', '辛'] },
      meridians: ['肺', '胃'],
      effects: ['淸熱瀉火', '除煩止渴'],
      indications: ['외감열병(外感熱病)', '고열번갈(高熱煩渴)', '폐열천해(肺熱喘咳)', '위화두통(胃火頭痛)', '치통(齒痛)'],
      cautions: ['비위허한 금기', '음허내열(陰虛內熱) 주의'],
      category: '清熱藥',
      dosage: '15~60g (先煎)',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 理氣藥 ──
    {
      id: 'HERB-022',
      nameKo: '진피',
      nameHanja: '陳皮',
      nameLatin: 'Citrus reticulata Blanco',
      properties: { nature: '溫', taste: ['辛', '苦'] },
      meridians: ['脾', '肺'],
      effects: ['理氣健脾', '燥濕化痰'],
      indications: ['완복창만(脘腹脹滿)', '식소구토(食少嘔吐)', '해수담다(咳嗽痰多)'],
      cautions: ['기허, 음허조해(陰虛燥咳) 주의'],
      category: '理氣藥',
      dosage: '3~10g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-023',
      nameKo: '향부자',
      nameHanja: '香附子',
      nameLatin: 'Cyperus rotundus L.',
      properties: { nature: '平', taste: ['辛', '微苦', '微甘'] },
      meridians: ['肝', '脾', '三焦'],
      effects: ['疏肝解鬱', '理氣寬中', '調經止痛'],
      indications: ['간기울체(肝氣鬱滯)', '협늑창통(脇肋脹痛)', '월경부조', '경행복통(經行腹痛)'],
      cautions: ['기허무체(氣虛無滯) 금기', '음허혈열(陰虛血熱) 주의'],
      category: '理氣藥',
      dosage: '6~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 活血祛瘀藥 ──
    {
      id: 'HERB-024',
      nameKo: '천궁',
      nameHanja: '川芎',
      nameLatin: 'Cnidium officinale Makino',
      properties: { nature: '溫', taste: ['辛'] },
      meridians: ['肝', '膽', '心包'],
      effects: ['活血行氣', '祛風止痛'],
      indications: ['월경부조', '경폐통경', '산후어로(産後瘀露)', '흉협동통(胸脇疼痛)', '두통(頭痛)'],
      cautions: ['음허화왕 금기', '월경과다(月經過多) 주의', '임산부 주의'],
      category: '活血祛瘀藥',
      dosage: '3~9g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-025',
      nameKo: '도인',
      nameHanja: '桃仁',
      nameLatin: 'Prunus persica (L.) Batsch',
      properties: { nature: '平', taste: ['苦', '甘'] },
      meridians: ['心', '肝', '大腸'],
      effects: ['活血祛瘀', '潤腸通便', '止咳平喘'],
      indications: ['경폐통경', '산후어조(産後瘀阻)', '징가(癥瘕)', '장조변비(腸燥便秘)', '해수천식'],
      cautions: ['임산부 금기', '월경과다 금기'],
      category: '活血祛瘀藥',
      dosage: '5~10g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-026',
      nameKo: '홍화',
      nameHanja: '紅花',
      nameLatin: 'Carthamus tinctorius L.',
      properties: { nature: '溫', taste: ['辛'] },
      meridians: ['心', '肝'],
      effects: ['活血通經', '散瘀止痛'],
      indications: ['경폐통경', '산후어조', '징가적취(癥瘕積聚)', '질타손상(跌打損傷)', '창양종통(瘡瘍腫痛)'],
      cautions: ['임산부 금기', '월경과다 금기'],
      category: '活血祛瘀藥',
      dosage: '3~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 化痰止咳平喘藥 ──
    {
      id: 'HERB-027',
      nameKo: '반하',
      nameHanja: '半夏',
      nameLatin: 'Pinellia ternata (Thunb.) Makino',
      properties: { nature: '溫', taste: ['辛'] },
      meridians: ['脾', '胃', '肺'],
      effects: ['燥濕化痰', '降逆止嘔', '消痞散結'],
      indications: ['습담해수(濕痰咳嗽)', '구토반위(嘔吐反胃)', '심하비만(心下痞滿)', '매핵기(梅核氣)'],
      cautions: ['오두(烏頭)와 배오 금기', '음허조해 금기', '생용(生用) 시 독성 주의'],
      category: '化痰止咳平喘藥',
      dosage: '3~9g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-028',
      nameKo: '길경',
      nameHanja: '桔梗',
      nameLatin: 'Platycodon grandiflorus (Jacq.) A.DC.',
      properties: { nature: '平', taste: ['苦', '辛'] },
      meridians: ['肺'],
      effects: ['宣肺', '利咽', '祛痰', '排膿'],
      indications: ['해수담다', '인후종통', '폐옹토농(肺癰吐膿)', '흉만협통(胸滿脇痛)'],
      cautions: ['음허구해(陰虛久咳) 주의', '토혈(吐血) 금기'],
      category: '化痰止咳平喘藥',
      dosage: '3~10g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-029',
      nameKo: '행인',
      nameHanja: '杏仁',
      nameLatin: 'Prunus armeniaca L.',
      properties: { nature: '微溫', taste: ['苦'] },
      meridians: ['肺', '大腸'],
      effects: ['降氣止咳平喘', '潤腸通便'],
      indications: ['해수기천(咳嗽氣喘)', '흉만담다(胸滿痰多)', '장조변비'],
      cautions: ['유아 과량 금기 (독성)', '음허해수 주의'],
      category: '化痰止咳平喘藥',
      dosage: '5~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 利水滲濕藥 ──
    {
      id: 'HERB-030',
      nameKo: '복령',
      nameHanja: '茯苓',
      nameLatin: 'Poria cocos (Schw.) Wolf',
      properties: { nature: '平', taste: ['甘', '淡'] },
      meridians: ['心', '肺', '脾', '腎'],
      effects: ['利水滲濕', '健脾寧心'],
      indications: ['수종뇨소(水腫尿少)', '담음현훈(痰飲眩暈)', '비허식소(脾虛食少)', '심신불안(心神不安)', '실면(失眠)'],
      cautions: ['허한활정(虛寒滑精) 주의'],
      category: '利水滲濕藥',
      dosage: '10~15g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-031',
      nameKo: '택사',
      nameHanja: '澤瀉',
      nameLatin: 'Alisma orientale (Sam.) Juz.',
      properties: { nature: '寒', taste: ['甘'] },
      meridians: ['腎', '膀胱'],
      effects: ['利水滲濕', '泄熱通淋'],
      indications: ['소변불리(小便不利)', '수종(水腫)', '설사(泄瀉)', '임병(淋病)', '현훈(眩暈)'],
      cautions: ['신허정활(腎虛精滑) 주의'],
      category: '利水滲濕藥',
      dosage: '6~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 溫裏藥 ──
    {
      id: 'HERB-032',
      nameKo: '부자',
      nameHanja: '附子',
      nameLatin: 'Aconitum carmichaelii Debeaux',
      properties: { nature: '大熱', taste: ['辛', '甘'] },
      meridians: ['心', '腎', '脾'],
      effects: ['回陽救逆', '補火助陽', '散寒止痛'],
      indications: ['망양증(亡陽證)', '사지궐역(四肢厥逆)', '양위(陽痿)', '궁냉(宮冷)', '한습비통(寒濕痹痛)'],
      cautions: ['독성 강함 — 반드시 포제(炮製) 후 사용', '반하, 과루, 패모, 백급, 백렴과 배오 금기', '임산부 금기'],
      category: '溫裏藥',
      dosage: '3~15g (先煎 30~60분)',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-033',
      nameKo: '건강',
      nameHanja: '乾薑',
      nameLatin: 'Zingiber officinale Roscoe',
      properties: { nature: '熱', taste: ['辛'] },
      meridians: ['脾', '胃', '腎', '心', '肺'],
      effects: ['溫中散寒', '回陽通脈', '溫肺化飮'],
      indications: ['완복냉통(脘腹冷痛)', '구토설사(嘔吐泄瀉)', '사지궐역(四肢厥逆)', '한음천해(寒飮喘咳)'],
      cautions: ['음허내열 금기', '임산부 주의'],
      category: '溫裏藥',
      dosage: '3~10g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-034',
      nameKo: '생강',
      nameHanja: '生薑',
      nameLatin: 'Zingiber officinale Roscoe (신선)',
      properties: { nature: '微溫', taste: ['辛'] },
      meridians: ['肺', '脾', '胃'],
      effects: ['解表散寒', '溫中止嘔', '化痰止咳', '解魚蟹毒'],
      indications: ['풍한감모', '구토(嘔吐)', '해수(咳嗽)', '어해중독(魚蟹中毒)'],
      cautions: ['음허내열 금기'],
      category: '溫裏藥',
      dosage: '3~9g',
      source: makeSource('동의보감 탕액편'),
    },

    // ── 補陰藥 ──
    {
      id: 'HERB-035',
      nameKo: '맥문동',
      nameHanja: '麥門冬',
      nameLatin: 'Ophiopogon japonicus (Thunb.) Ker Gawl.',
      properties: { nature: '微寒', taste: ['甘', '微苦'] },
      meridians: ['心', '肺', '胃'],
      effects: ['養陰生津', '潤肺清心'],
      indications: ['폐조건해(肺燥乾咳)', '음허노수(陰虛勞嗽)', '인건구갈(咽乾口渴)', '심번실면(心煩失眠)', '장조변비'],
      cautions: ['비위허한 설사 주의', '담습(痰濕) 주의'],
      category: '補陰藥',
      dosage: '6~12g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-036',
      nameKo: '구기자',
      nameHanja: '枸杞子',
      nameLatin: 'Lycium chinense Mill.',
      properties: { nature: '平', taste: ['甘'] },
      meridians: ['肝', '腎'],
      effects: ['滋補肝腎', '益精明目'],
      indications: ['간신음허', '요슬산연', '현훈(眩暈)', '목암부명(目暗不明)', '유정(遺精)'],
      cautions: ['비허습체(脾虛濕滯) 주의', '외감실열(外感實熱) 금기'],
      category: '補陰藥',
      dosage: '6~12g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 補陽藥 ──
    {
      id: 'HERB-037',
      nameKo: '녹용',
      nameHanja: '鹿茸',
      nameLatin: 'Cervus nippon Temminck (cornu)',
      properties: { nature: '溫', taste: ['甘', '鹹'] },
      meridians: ['腎', '肝'],
      effects: ['壯腎陽', '益精血', '強筋骨', '調衝任', '托瘡毒'],
      indications: ['신양부족(腎陽不足)', '정혈휴핍(精血虧乏)', '양위(陽痿)', '궁냉불임(宮冷不孕)', '소아발육부진(小兒發育不振)'],
      cautions: ['음허화왕 금기', '실열증 금기'],
      category: '補陽藥',
      dosage: '1~2g (연말 충복)',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-038',
      nameKo: '두충',
      nameHanja: '杜仲',
      nameLatin: 'Eucommia ulmoides Oliv.',
      properties: { nature: '溫', taste: ['甘'] },
      meridians: ['肝', '腎'],
      effects: ['補肝腎', '強筋骨', '安胎'],
      indications: ['요슬산통(腰膝痠痛)', '양위유정(陽痿遺精)', '태동불안(胎動不安)', '두훈목현(頭暈目眩)'],
      cautions: ['음허화왕 주의'],
      category: '補陽藥',
      dosage: '6~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 安神藥 ──
    {
      id: 'HERB-039',
      nameKo: '산조인',
      nameHanja: '酸棗仁',
      nameLatin: 'Ziziphus jujuba Mill. var. spinosa',
      properties: { nature: '平', taste: ['甘', '酸'] },
      meridians: ['心', '肝', '膽'],
      effects: ['養心補肝', '寧心安神', '斂汗生津'],
      indications: ['허번불면(虛煩不眠)', '심계(心悸)', '다몽(多夢)', '체허다한(體虛多汗)', '진액부족(津液不足)'],
      cautions: ['실사울화(實邪鬱火) 금기'],
      category: '安神藥',
      dosage: '10~15g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-040',
      nameKo: '원지',
      nameHanja: '遠志',
      nameLatin: 'Polygala tenuifolia Willd.',
      properties: { nature: '溫', taste: ['苦', '辛'] },
      meridians: ['心', '腎', '肺'],
      effects: ['安神益智', '祛痰開竅', '消散癰腫'],
      indications: ['심신불안', '실면다몽(失眠多夢)', '건망경계(健忘驚悸)', '해수담다', '옹저창양(癰疽瘡瘍)'],
      cautions: ['위염, 궤양 환자 주의 (자극성)'],
      category: '安神藥',
      dosage: '3~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 消食藥 ──
    {
      id: 'HERB-041',
      nameKo: '산사',
      nameHanja: '山楂',
      nameLatin: 'Crataegus pinnatifida Bge.',
      properties: { nature: '微溫', taste: ['酸', '甘'] },
      meridians: ['脾', '胃', '肝'],
      effects: ['消食健胃', '行氣散瘀', '化濁降脂'],
      indications: ['육식적체(肉食積滯)', '완복창만', '설사복통(泄瀉腹痛)', '어혈경폐(瘀血經閉)', '고지혈증(高脂血症)'],
      cautions: ['비위허약으로 무적체(無積滯) 시 주의', '산미(酸味)로 위산과다 주의'],
      category: '消食藥',
      dosage: '10~15g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 收澁藥 ──
    {
      id: 'HERB-042',
      nameKo: '오미자',
      nameHanja: '五味子',
      nameLatin: 'Schisandra chinensis (Turcz.) Baill.',
      properties: { nature: '溫', taste: ['酸', '甘'] },
      meridians: ['肺', '心', '腎'],
      effects: ['收斂固澁', '益氣生津', '補腎寧心'],
      indications: ['구해허천(久咳虛喘)', '자한도한', '유정활정(遺精滑精)', '구사(久瀉)', '심계실면'],
      cautions: ['외감해수(外感咳嗽) 초기 금기', '실열(實熱) 금기'],
      category: '收澁藥',
      dosage: '2~6g',
      source: makeSource('동의보감 탕액편'),
    },

    // ── 平肝息風藥 ──
    {
      id: 'HERB-043',
      nameKo: '천마',
      nameHanja: '天麻',
      nameLatin: 'Gastrodia elata Bl.',
      properties: { nature: '平', taste: ['甘'] },
      meridians: ['肝'],
      effects: ['息風止痙', '平抑肝陽', '祛風通絡'],
      indications: ['소아경풍(小兒驚風)', '전간추축(癲癇抽搐)', '현훈두통', '간풍내동(肝風內動)', '지체마목(肢體麻木)'],
      cautions: ['혈허생풍(血虛生風) 시 단독 사용 주의'],
      category: '平肝息風藥',
      dosage: '3~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 祛風濕藥 ──
    {
      id: 'HERB-044',
      nameKo: '독활',
      nameHanja: '獨活',
      nameLatin: 'Angelica pubescens Maxim.',
      properties: { nature: '微溫', taste: ['辛', '苦'] },
      meridians: ['腎', '膀胱'],
      effects: ['祛風除濕', '通痹止痛'],
      indications: ['풍한습비(風寒濕痹)', '요슬동통', '소음두통(少陰頭痛)'],
      cautions: ['음허화왕 주의'],
      category: '祛風濕藥',
      dosage: '3~10g',
      source: makeSource('OASIS 한약재 DB'),
    },

    // ── 瀉下藥 ──
    {
      id: 'HERB-045',
      nameKo: '대황',
      nameHanja: '大黃',
      nameLatin: 'Rheum palmatum L.',
      properties: { nature: '寒', taste: ['苦'] },
      meridians: ['脾', '胃', '大腸', '肝', '心包'],
      effects: ['瀉下攻積', '淸熱瀉火', '涼血解毒', '逐瘀通經'],
      indications: ['실열변비(實熱便秘)', '복통적체(腹痛積滯)', '사리부상(瀉痢不爽)', '습열황달', '혈열출혈(血熱出血)'],
      cautions: ['임산부 금기', '수유기 금기', '비위허약 금기', '월경기 주의'],
      category: '瀉下藥',
      dosage: '3~15g (後下)',
      source: makeSource('동의보감 탕액편'),
    },

    // ── 기타 상용약 ──
    {
      id: 'HERB-046',
      nameKo: '대조',
      nameHanja: '大棗',
      nameLatin: 'Ziziphus jujuba Mill.',
      properties: { nature: '溫', taste: ['甘'] },
      meridians: ['脾', '胃', '心'],
      effects: ['補中益氣', '養血安神', '緩和藥性'],
      indications: ['비기허약', '혈허위황', '부인장조(婦人臟躁)', '약성조화(藥性調和)'],
      cautions: ['습담정만(濕痰停滿) 주의', '치아 손상 주의'],
      category: '補氣藥',
      dosage: '6~15g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-047',
      nameKo: '시호',
      nameHanja: '柴胡',
      nameLatin: 'Bupleurum falcatum L.',
      properties: { nature: '微寒', taste: ['苦', '辛'] },
      meridians: ['肝', '膽', '肺'],
      effects: ['和解表裏', '疏肝升陽'],
      indications: ['한열왕래(寒熱往來)', '흉협고만(胸脇苦滿)', '구고(口苦)', '월경부조', '자궁탈수(子宮脫垂)'],
      cautions: ['간양상항(肝陽上亢) 금기', '음허화왕 금기'],
      category: '解表藥',
      dosage: '3~9g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-048',
      nameKo: '지황',
      nameHanja: '地黃',
      nameLatin: 'Rehmannia glutinosa (Gaertn.) Libosch. (생지황)',
      properties: { nature: '寒', taste: ['甘', '苦'] },
      meridians: ['心', '肝', '腎'],
      effects: ['淸熱涼血', '養陰生津'],
      indications: ['열입영혈(熱入營血)', '구갈(口渴)', '혈열출혈', '진상소갈(津傷消渴)'],
      cautions: ['비위허한 주의', '복만설사(腹滿泄瀉) 주의'],
      category: '清熱藥',
      dosage: '10~15g',
      source: makeSource('동의보감 탕액편'),
    },
    {
      id: 'HERB-049',
      nameKo: '목단피',
      nameHanja: '牧丹皮',
      nameLatin: 'Paeonia suffruticosa Andrews',
      properties: { nature: '微寒', taste: ['苦', '辛'] },
      meridians: ['心', '肝', '腎'],
      effects: ['淸熱涼血', '活血化瘀'],
      indications: ['온독발반(溫毒發斑)', '혈열토뉵(血熱吐衄)', '경폐통경', '옹종창양(癰腫瘡瘍)', '골증조열'],
      cautions: ['혈허유한(血虛有寒) 금기', '월경과다 금기', '임산부 금기'],
      category: '清熱藥',
      dosage: '6~12g',
      source: makeSource('OASIS 한약재 DB'),
    },
    {
      id: 'HERB-050',
      nameKo: '사인',
      nameHanja: '砂仁',
      nameLatin: 'Amomum villosum Lour.',
      properties: { nature: '溫', taste: ['辛'] },
      meridians: ['脾', '胃', '腎'],
      effects: ['化濕開胃', '溫脾止瀉', '理氣安胎'],
      indications: ['습조중조(濕阻中焦)', '완복창만', '비위허한 구토설사', '임신오조(姙娠惡阻)', '태동불안'],
      cautions: ['음허혈조(陰虛血燥) 금기', '후하(後下)'],
      category: '化濕藥',
      dosage: '3~6g (後下)',
      source: makeSource('OASIS 한약재 DB'),
    },
  ];

  return {
    dataType: 'herbs',
    version: '1.0.0-sample',
    generatedAt: NOW,
    totalCount: entries.length,
    entries,
  };
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 3. 처방 데이터 (대표 처방 30건)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function generatePrescriptions(): PrescriptionCollection {
  const entries: PrescriptionEntry[] = [
    {
      id: 'RX-001',
      nameKo: '갈근탕',
      nameHanja: '葛根湯',
      ingredients: [
        { herbNameKo: '갈근', herbNameHanja: '葛根', amount: '8g', role: '君' },
        { herbNameKo: '마황', herbNameHanja: '麻黃', amount: '4g', role: '臣' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '4g', role: '佐' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
      ],
      effects: ['發汗解表', '生津舒筋'],
      indications: ['외감풍한(外感風寒)', '항배강기(項背强几几)', '무한오풍(無汗惡風)', '두통발열(頭痛發熱)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-002',
      nameKo: '소시호탕',
      nameHanja: '小柴胡湯',
      ingredients: [
        { herbNameKo: '시호', herbNameHanja: '柴胡', amount: '8g', role: '君' },
        { herbNameKo: '황금', herbNameHanja: '黃芩', amount: '3g', role: '臣' },
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '5g', role: '佐' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '4g', role: '佐' },
      ],
      effects: ['和解少陽'],
      indications: ['한열왕래(寒熱往來)', '흉협고만(胸脇苦滿)', '묵묵불욕음식(默默不欲飮食)', '심번희구(心煩喜嘔)', '구고(口苦)', '인건(咽乾)', '목현(目眩)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-003',
      nameKo: '쌍화탕',
      nameHanja: '雙和湯',
      ingredients: [
        { herbNameKo: '숙지황', herbNameHanja: '熟地黃', amount: '4g', role: '君' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '4g', role: '君' },
        { herbNameKo: '황기', herbNameHanja: '黃芪', amount: '4g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '4g', role: '臣' },
        { herbNameKo: '천궁', herbNameHanja: '川芎', amount: '3g', role: '佐' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '3g', role: '佐' },
      ],
      effects: ['益氣補血', '調和營衛'],
      indications: ['기혈양허(氣血兩虛)', '노권상(勞倦傷)', '두통신통(頭痛身痛)', '오한발열(惡寒發熱)'],
      usage: '물에 달여 복용',
      classicSource: '동의보감(東醫寶鑑)',
      source: makeSource('동의보감'),
    },
    {
      id: 'RX-004',
      nameKo: '사물탕',
      nameHanja: '四物湯',
      ingredients: [
        { herbNameKo: '숙지황', herbNameHanja: '熟地黃', amount: '4g', role: '君' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '천궁', herbNameHanja: '川芎', amount: '3g', role: '使' },
      ],
      effects: ['補血調血'],
      indications: ['영혈허체(營血虛滯)', '월경부조', '경행복통', '붕루(崩漏)', '두훈목현(頭暈目眩)', '심계실면'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-005',
      nameKo: '육미지황환',
      nameHanja: '六味地黃丸',
      ingredients: [
        { herbNameKo: '숙지황', herbNameHanja: '熟地黃', amount: '8g', role: '君' },
        { herbNameKo: '산수유', herbNameHanja: '山茱萸', amount: '4g', role: '臣' },
        { herbNameKo: '산약', herbNameHanja: '山藥', amount: '4g', role: '臣' },
        { herbNameKo: '택사', herbNameHanja: '澤瀉', amount: '3g', role: '佐' },
        { herbNameKo: '목단피', herbNameHanja: '牧丹皮', amount: '3g', role: '佐' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '佐' },
      ],
      effects: ['滋補肝腎'],
      indications: ['간신음허(肝腎陰虛)', '요슬산연', '두훈이명(頭暈耳鳴)', '도한유정(盜汗遺精)', '골증조열', '소갈(消渴)'],
      usage: '환(丸)으로 복용 또는 탕제',
      classicSource: '소아약증직결(小兒藥證直訣)',
      source: makeSource('소아약증직결'),
    },
    {
      id: 'RX-006',
      nameKo: '사군자탕',
      nameHanja: '四君子湯',
      ingredients: [
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '4g', role: '君' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '4g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '4g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
      ],
      effects: ['益氣健脾'],
      indications: ['비위기허(脾胃氣虛)', '면색위백(面色萎白)', '어성저미(語聲低微)', '식소편당(食少便溏)', '사지무력(四肢無力)'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-007',
      nameKo: '보중익기탕',
      nameHanja: '補中益氣湯',
      ingredients: [
        { herbNameKo: '황기', herbNameHanja: '黃芪', amount: '6g', role: '君' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '臣' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '臣' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '3g', role: '佐' },
        { herbNameKo: '진피', herbNameHanja: '陳皮', amount: '2g', role: '佐' },
        { herbNameKo: '승마', herbNameHanja: '升麻', amount: '1g', role: '佐' },
        { herbNameKo: '시호', herbNameHanja: '柴胡', amount: '1g', role: '佐' },
      ],
      effects: ['補中益氣', '升陽舉陷'],
      indications: ['비위기허', '중기하함', '식소체권(食少體倦)', '장조지탈(臟躁脫肛)', '자궁탈수'],
      usage: '물에 달여 복용',
      classicSource: '비위론(脾胃論)',
      source: makeSource('비위론'),
    },
    {
      id: 'RX-008',
      nameKo: '십전대보탕',
      nameHanja: '十全大補湯',
      ingredients: [
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '君' },
        { herbNameKo: '황기', herbNameHanja: '黃芪', amount: '3g', role: '君' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '臣' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '3g', role: '臣' },
        { herbNameKo: '숙지황', herbNameHanja: '熟地黃', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '천궁', herbNameHanja: '川芎', amount: '3g', role: '佐' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '2g', role: '佐' },
      ],
      effects: ['溫補氣血'],
      indications: ['기혈양허', '면색창백(面色蒼白)', '두훈(頭暈)', '사지불온(四肢不溫)', '식소핍력(食少乏力)'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-009',
      nameKo: '계지탕',
      nameHanja: '桂枝湯',
      ingredients: [
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '4g', role: '君' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '4g', role: '臣' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '佐' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '4g', role: '佐' },
      ],
      effects: ['解肌發表', '調和營衛'],
      indications: ['외감풍한(外感風寒)', '두통발열', '유한오풍(有汗惡風)', '비색(鼻塞)'],
      usage: '물에 달여 복용, 복용 후 따뜻한 죽을 먹어 발한 도움',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-010',
      nameKo: '마황탕',
      nameHanja: '麻黃湯',
      ingredients: [
        { herbNameKo: '마황', herbNameHanja: '麻黃', amount: '5g', role: '君' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '4g', role: '臣' },
        { herbNameKo: '행인', herbNameHanja: '杏仁', amount: '5g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
      ],
      effects: ['發汗解表', '宣肺平喘'],
      indications: ['외감풍한표실증(外感風寒表實證)', '오한발열', '두신동통(頭身疼痛)', '무한이천(無汗而喘)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-011',
      nameKo: '소청룡탕',
      nameHanja: '小靑龍湯',
      ingredients: [
        { herbNameKo: '마황', herbNameHanja: '麻黃', amount: '4g', role: '君' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '3g', role: '臣' },
        { herbNameKo: '건강', herbNameHanja: '乾薑', amount: '3g', role: '臣' },
        { herbNameKo: '세신', herbNameHanja: '細辛', amount: '2g', role: '佐' },
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '4g', role: '佐' },
        { herbNameKo: '오미자', herbNameHanja: '五味子', amount: '3g', role: '佐' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
      ],
      effects: ['解表散寒', '溫肺化飮'],
      indications: ['풍한속음(風寒束飮)', '해수천식', '담다청희(痰多清稀)', '불득평와(不得平臥)', '비색유제(鼻塞流涕)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-012',
      nameKo: '이중탕',
      nameHanja: '理中湯',
      ingredients: [
        { herbNameKo: '건강', herbNameHanja: '乾薑', amount: '4g', role: '君' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '臣' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '3g', role: '使' },
      ],
      effects: ['溫中祛寒', '補氣健脾'],
      indications: ['비위허한', '자리부지(自利不渴)', '완복동통', '구토(嘔吐)', '식곡불화(食穀不化)'],
      usage: '물에 달여 복용 또는 환제',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-013',
      nameKo: '귀비탕',
      nameHanja: '歸脾湯',
      ingredients: [
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '君' },
        { herbNameKo: '황기', herbNameHanja: '黃芪', amount: '3g', role: '君' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '臣' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '2g', role: '佐' },
        { herbNameKo: '산조인', herbNameHanja: '酸棗仁', amount: '3g', role: '佐' },
        { herbNameKo: '원지', herbNameHanja: '遠志', amount: '2g', role: '佐' },
        { herbNameKo: '용안육', herbNameHanja: '龍眼肉', amount: '3g', role: '佐' },
        { herbNameKo: '목향', herbNameHanja: '木香', amount: '1.5g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '3g', role: '佐' },
      ],
      effects: ['益氣補血', '健脾養心'],
      indications: ['심비양허(心脾兩虛)', '기혈부족', '심계정충(心悸怔忡)', '실면건망(失眠健忘)', '비불통혈(脾不統血)', '붕루(崩漏)'],
      usage: '물에 달여 복용',
      classicSource: '제생방(濟生方)',
      source: makeSource('제생방'),
    },
    {
      id: 'RX-014',
      nameKo: '온담탕',
      nameHanja: '溫膽湯',
      ingredients: [
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '5g', role: '君' },
        { herbNameKo: '진피', herbNameHanja: '陳皮', amount: '3g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '4g', role: '臣' },
        { herbNameKo: '지실', herbNameHanja: '枳實', amount: '2g', role: '佐' },
        { herbNameKo: '죽여', herbNameHanja: '竹茹', amount: '2g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '2g', role: '佐' },
      ],
      effects: ['理氣化痰', '和胃利膽'],
      indications: ['담울상요(膽鬱上擾)', '허번불면', '구역탄산(嘔逆呑酸)', '경계불안(驚悸不安)', '전간(癲癇)'],
      usage: '물에 달여 복용',
      classicSource: '비급천금요방(備急千金要方)',
      source: makeSource('비급천금요방'),
    },
    {
      id: 'RX-015',
      nameKo: '팔정산',
      nameHanja: '八正散',
      ingredients: [
        { herbNameKo: '차전자', herbNameHanja: '車前子', amount: '4g', role: '君' },
        { herbNameKo: '구맥', herbNameHanja: '瞿麥', amount: '4g', role: '臣' },
        { herbNameKo: '편축', herbNameHanja: '萹蓄', amount: '4g', role: '臣' },
        { herbNameKo: '활석', herbNameHanja: '滑石', amount: '4g', role: '臣' },
        { herbNameKo: '치자', herbNameHanja: '梔子', amount: '3g', role: '佐' },
        { herbNameKo: '대황', herbNameHanja: '大黃', amount: '2g', role: '佐' },
        { herbNameKo: '목통', herbNameHanja: '木通', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
      ],
      effects: ['淸熱瀉火', '利水通淋'],
      indications: ['습열하주(濕熱下注)', '열림(熱淋)', '혈림(血淋)', '소변빈급삽통(小便頻急澁痛)', '뇨색혼탁(尿色混濁)'],
      usage: '물에 달여 복용, 등심(燈心) 추가',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-016',
      nameKo: '소요산',
      nameHanja: '逍遙散',
      ingredients: [
        { herbNameKo: '시호', herbNameHanja: '柴胡', amount: '4g', role: '君' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '臣' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '佐' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1.5g', role: '使' },
        { herbNameKo: '박하', herbNameHanja: '薄荷', amount: '1g', role: '佐' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '2g', role: '佐' },
      ],
      effects: ['疏肝解鬱', '養血健脾'],
      indications: ['간울비허(肝鬱脾虛)', '양협작통(兩脇作痛)', '두통목현', '구조인건(口燥咽乾)', '신피식소(神疲食少)', '월경부조'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-017',
      nameKo: '평위산',
      nameHanja: '平胃散',
      ingredients: [
        { herbNameKo: '창출', herbNameHanja: '蒼朮', amount: '5g', role: '君' },
        { herbNameKo: '후박', herbNameHanja: '厚朴', amount: '3g', role: '臣' },
        { herbNameKo: '진피', herbNameHanja: '陳皮', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '2g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '3g', role: '佐' },
      ],
      effects: ['燥濕運脾', '行氣和胃'],
      indications: ['습곤비위(濕困脾胃)', '완복창만', '불사음식(不思飮食)', '구담불갈(口淡不渴)', '오심구토(惡心嘔吐)'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-018',
      nameKo: '오령산',
      nameHanja: '五苓散',
      ingredients: [
        { herbNameKo: '택사', herbNameHanja: '澤瀉', amount: '5g', role: '君' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '臣' },
        { herbNameKo: '저령', herbNameHanja: '豬苓', amount: '3g', role: '臣' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '佐' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '2g', role: '使' },
      ],
      effects: ['利水滲濕', '溫陽化氣'],
      indications: ['수습내정(水濕內停)', '소변불리', '수종(水腫)', '설사(泄瀉)', '담음(痰飮)'],
      usage: '산(散)으로 복용 또는 탕전',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-019',
      nameKo: '생맥산',
      nameHanja: '生脈散',
      ingredients: [
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '5g', role: '君' },
        { herbNameKo: '맥문동', herbNameHanja: '麥門冬', amount: '5g', role: '臣' },
        { herbNameKo: '오미자', herbNameHanja: '五味子', amount: '3g', role: '佐' },
      ],
      effects: ['益氣生津', '斂陰止汗'],
      indications: ['온열서사(溫熱暑邪)', '기음양상(氣陰兩傷)', '한다체권(汗多體倦)', '기단구갈(氣短口渴)', '맥허욕절(脈虛欲絕)'],
      usage: '물에 달여 복용',
      classicSource: '의학계원(醫學啓源)',
      source: makeSource('의학계원'),
    },
    {
      id: 'RX-020',
      nameKo: '대승기탕',
      nameHanja: '大承氣湯',
      ingredients: [
        { herbNameKo: '대황', herbNameHanja: '大黃', amount: '6g', role: '君' },
        { herbNameKo: '후박', herbNameHanja: '厚朴', amount: '5g', role: '臣' },
        { herbNameKo: '지실', herbNameHanja: '枳實', amount: '3g', role: '臣' },
        { herbNameKo: '망초', herbNameHanja: '芒硝', amount: '3g', role: '佐' },
      ],
      effects: ['峻下熱結'],
      indications: ['양명부실(陽明腑實)', '대변불통(大便不通)', '복만동통거안(腹滿疼痛拒按)', '조실조비(燥屎燥秘)', '고열신혼(高熱神昏)'],
      usage: '물에 달여 복용 (대황 후하, 망초 용화)',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-021',
      nameKo: '백호탕',
      nameHanja: '白虎湯',
      ingredients: [
        { herbNameKo: '석고', herbNameHanja: '石膏', amount: '30g', role: '君' },
        { herbNameKo: '지모', herbNameHanja: '知母', amount: '6g', role: '臣' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '갱미', herbNameHanja: '粳米', amount: '6g', role: '佐' },
      ],
      effects: ['淸熱生津'],
      indications: ['양명경증(陽明經證)', '장양열성(壯陽熱盛)', '고열번갈(高熱煩渴)', '한출오열(汗出惡熱)', '맥홍대(脈洪大)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-022',
      nameKo: '천왕보심단',
      nameHanja: '天王補心丹',
      ingredients: [
        { herbNameKo: '생지황', herbNameHanja: '生地黃', amount: '8g', role: '君' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '2g', role: '臣' },
        { herbNameKo: '단삼', herbNameHanja: '丹蔘', amount: '2g', role: '臣' },
        { herbNameKo: '현삼', herbNameHanja: '玄蔘', amount: '2g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '2g', role: '佐' },
        { herbNameKo: '오미자', herbNameHanja: '五味子', amount: '2g', role: '佐' },
        { herbNameKo: '원지', herbNameHanja: '遠志', amount: '2g', role: '佐' },
        { herbNameKo: '길경', herbNameHanja: '桔梗', amount: '2g', role: '佐' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '2g', role: '佐' },
        { herbNameKo: '천문동', herbNameHanja: '天門冬', amount: '2g', role: '佐' },
        { herbNameKo: '맥문동', herbNameHanja: '麥門冬', amount: '2g', role: '佐' },
        { herbNameKo: '산조인', herbNameHanja: '酸棗仁', amount: '2g', role: '佐' },
        { herbNameKo: '백자인', herbNameHanja: '柏子仁', amount: '2g', role: '佐' },
      ],
      effects: ['滋陰養血', '補心安神'],
      indications: ['심음부족(心陰不足)', '심계실면', '허번(虛煩)', '신피건망', '대변조결(大便燥結)', '구설생창(口舌生瘡)'],
      usage: '꿀과 함께 환으로 복용 또는 탕전',
      classicSource: '세의득효방(世醫得效方)',
      source: makeSource('세의득효방'),
    },
    {
      id: 'RX-023',
      nameKo: '독활기생탕',
      nameHanja: '獨活寄生湯',
      ingredients: [
        { herbNameKo: '독활', herbNameHanja: '獨活', amount: '3g', role: '君' },
        { herbNameKo: '상기생', herbNameHanja: '桑寄生', amount: '3g', role: '臣' },
        { herbNameKo: '두충', herbNameHanja: '杜仲', amount: '3g', role: '臣' },
        { herbNameKo: '우슬', herbNameHanja: '牛膝', amount: '3g', role: '臣' },
        { herbNameKo: '세신', herbNameHanja: '細辛', amount: '1g', role: '佐' },
        { herbNameKo: '방풍', herbNameHanja: '防風', amount: '3g', role: '佐' },
        { herbNameKo: '진교', herbNameHanja: '秦艽', amount: '3g', role: '佐' },
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '3g', role: '佐' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '숙지황', herbNameHanja: '熟地黃', amount: '3g', role: '佐' },
        { herbNameKo: '천궁', herbNameHanja: '川芎', amount: '2g', role: '佐' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '2g', role: '佐' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1g', role: '使' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '2g', role: '佐' },
      ],
      effects: ['祛風濕', '止痹痛', '益肝腎', '補氣血'],
      indications: ['비증일구(痹證日久)', '간신양허(肝腎兩虛)', '기혈부족', '요슬동통', '관절굴신불리(關節屈伸不利)', '심계기단(心悸氣短)'],
      usage: '물에 달여 복용',
      classicSource: '비급천금요방(備急千金要方)',
      source: makeSource('비급천금요방'),
    },
    {
      id: 'RX-024',
      nameKo: '산사소도환',
      nameHanja: '保和丸',
      ingredients: [
        { herbNameKo: '산사', herbNameHanja: '山楂', amount: '6g', role: '君' },
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '3g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '佐' },
        { herbNameKo: '진피', herbNameHanja: '陳皮', amount: '2g', role: '佐' },
        { herbNameKo: '내복자', herbNameHanja: '萊菔子', amount: '2g', role: '佐' },
        { herbNameKo: '연교', herbNameHanja: '連翹', amount: '2g', role: '佐' },
        { herbNameKo: '신곡', herbNameHanja: '神麴', amount: '2g', role: '佐' },
      ],
      effects: ['消食和胃'],
      indications: ['식적정체(食積停滯)', '완복창만', '산식산부(酸食酸腐)', '오심구토', '대변불상(大便不爽)'],
      usage: '환(丸) 복용 또는 탕전',
      classicSource: '단계심법(丹溪心法)',
      source: makeSource('단계심법'),
    },
    {
      id: 'RX-025',
      nameKo: '삼소음',
      nameHanja: '蔘蘇飮',
      ingredients: [
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '君' },
        { herbNameKo: '소엽', herbNameHanja: '蘇葉', amount: '3g', role: '君' },
        { herbNameKo: '갈근', herbNameHanja: '葛根', amount: '3g', role: '臣' },
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '3g', role: '臣' },
        { herbNameKo: '전호', herbNameHanja: '前胡', amount: '3g', role: '佐' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '佐' },
        { herbNameKo: '길경', herbNameHanja: '桔梗', amount: '2g', role: '佐' },
        { herbNameKo: '지각', herbNameHanja: '枳殼', amount: '2g', role: '佐' },
        { herbNameKo: '진피', herbNameHanja: '陳皮', amount: '2g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '1g', role: '使' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '2g', role: '佐' },
      ],
      effects: ['益氣解表', '理氣化痰'],
      indications: ['기허외감(氣虛外感)', '신열두통(身熱頭痛)', '비색(鼻塞)', '해수담백(咳嗽痰白)', '흉민(胸悶)', '권태핍력(倦怠乏力)'],
      usage: '물에 달여 복용',
      classicSource: '태평혜민화제국방(太平惠民和劑局方)',
      source: makeSource('태평혜민화제국방'),
    },
    {
      id: 'RX-026',
      nameKo: '진무탕',
      nameHanja: '眞武湯',
      ingredients: [
        { herbNameKo: '부자', herbNameHanja: '附子', amount: '5g', role: '君' },
        { herbNameKo: '백출', herbNameHanja: '白朮', amount: '3g', role: '臣' },
        { herbNameKo: '복령', herbNameHanja: '茯苓', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '佐' },
        { herbNameKo: '생강', herbNameHanja: '生薑', amount: '3g', role: '佐' },
      ],
      effects: ['溫陽利水'],
      indications: ['양허수범(陽虛水泛)', '소변불리', '사지침중동통(四肢沈重疼痛)', '복통하리(腹痛下利)', '부종(浮腫)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-027',
      nameKo: '도핵승기탕',
      nameHanja: '桃核承氣湯',
      ingredients: [
        { herbNameKo: '도인', herbNameHanja: '桃仁', amount: '5g', role: '君' },
        { herbNameKo: '대황', herbNameHanja: '大黃', amount: '4g', role: '臣' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '2g', role: '佐' },
        { herbNameKo: '망초', herbNameHanja: '芒硝', amount: '2g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
      ],
      effects: ['逐瘀瀉熱'],
      indications: ['하초축혈(下焦蓄血)', '소복급결(少腹急結)', '소변자리(小便自利)', '신지여광(神志如狂)', '야열조퇴(夜熱早退)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-028',
      nameKo: '황련해독탕',
      nameHanja: '黃連解毒湯',
      ingredients: [
        { herbNameKo: '황련', herbNameHanja: '黃連', amount: '3g', role: '君' },
        { herbNameKo: '황금', herbNameHanja: '黃芩', amount: '3g', role: '臣' },
        { herbNameKo: '황백', herbNameHanja: '黃柏', amount: '3g', role: '佐' },
        { herbNameKo: '치자', herbNameHanja: '梔子', amount: '3g', role: '佐' },
      ],
      effects: ['瀉火解毒'],
      indications: ['삼초열성(三焦熱盛)', '대열번조(大熱煩躁)', '구조인건(口燥咽乾)', '착어(錯語)', '불면(不眠)', '열독발반(熱毒發斑)', '옹종정창(癰腫疔瘡)'],
      usage: '물에 달여 복용',
      classicSource: '외대비요(外臺秘要)',
      source: makeSource('외대비요'),
    },
    {
      id: 'RX-029',
      nameKo: '당귀사역탕',
      nameHanja: '當歸四逆湯',
      ingredients: [
        { herbNameKo: '당귀', herbNameHanja: '當歸', amount: '4g', role: '君' },
        { herbNameKo: '계지', herbNameHanja: '桂枝', amount: '3g', role: '臣' },
        { herbNameKo: '백작약', herbNameHanja: '白芍藥', amount: '3g', role: '臣' },
        { herbNameKo: '세신', herbNameHanja: '細辛', amount: '1g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '2g', role: '使' },
        { herbNameKo: '통초', herbNameHanja: '通草', amount: '2g', role: '佐' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '4g', role: '佐' },
      ],
      effects: ['溫經散寒', '養血通脈'],
      indications: ['혈허한궐(血虛寒厥)', '수족궐한(手足厥寒)', '맥세욕절(脈細欲絕)', '한산복통(寒疝腹痛)', '동상(凍瘡)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
    {
      id: 'RX-030',
      nameKo: '반하사심탕',
      nameHanja: '半夏瀉心湯',
      ingredients: [
        { herbNameKo: '반하', herbNameHanja: '半夏', amount: '5g', role: '君' },
        { herbNameKo: '황금', herbNameHanja: '黃芩', amount: '3g', role: '臣' },
        { herbNameKo: '건강', herbNameHanja: '乾薑', amount: '3g', role: '臣' },
        { herbNameKo: '황련', herbNameHanja: '黃連', amount: '1g', role: '佐' },
        { herbNameKo: '인삼', herbNameHanja: '人蔘', amount: '3g', role: '佐' },
        { herbNameKo: '감초', herbNameHanja: '甘草', amount: '3g', role: '使' },
        { herbNameKo: '대조', herbNameHanja: '大棗', amount: '4g', role: '佐' },
      ],
      effects: ['寒熱平調', '消痞散結'],
      indications: ['한열착잡(寒熱錯雜)', '심하비만(心下痞滿)', '구토구역(嘔吐嘔逆)', '장명설사(腸鳴泄瀉)'],
      usage: '물에 달여 복용',
      classicSource: '상한론(傷寒論)',
      source: makeSource('상한론'),
    },
  ];

  return {
    dataType: 'prescriptions',
    version: '1.0.0-sample',
    generatedAt: NOW,
    totalCount: entries.length,
    entries,
  };
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 메인 실행
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function writeJSON(dir: string, filename: string, data: unknown): void {
  mkdirSync(dir, { recursive: true });
  const filepath = join(dir, filename);
  writeFileSync(filepath, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`  ✓ ${filepath}`);
}

function main(): void {
  console.log('한의사AI 샘플 데이터 생성 시작...\n');

  // 1. 동의보감
  console.log('[1/3] 동의보감 경전 텍스트 생성');
  const dongeuibogam = generateDongeuibogam();
  writeJSON(DONGEUIBOGAM_DIR, 'dongeuibogam-samples.json', dongeuibogam);
  console.log(`  → ${dongeuibogam.totalCount}건 생성\n`);

  // 2. 약재
  console.log('[2/3] 약재 데이터 생성');
  const herbs = generateHerbs();
  writeJSON(HERBS_DIR, 'herbs-samples.json', herbs);
  console.log(`  → ${herbs.totalCount}건 생성\n`);

  // 3. 처방
  console.log('[3/3] 처방 데이터 생성');
  const prescriptions = generatePrescriptions();
  writeJSON(PRESCRIPTIONS_DIR, 'prescriptions-samples.json', prescriptions);
  console.log(`  → ${prescriptions.totalCount}건 생성\n`);

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('샘플 데이터 생성 완료!');
  console.log(`총 ${dongeuibogam.totalCount + herbs.totalCount + prescriptions.totalCount}건`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
}

main();
